name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy .env.test to .env
        run: cp .env.test .env

      - name: Start MySQL and MQTT services
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          pytest --cov=src tests/ --cov-report=xml

      # - name: Upload test coverage
      #   uses: codeclimate/test-reporter@v1
      #   with:
      #     format: 'lcov'
      #     lcov: './coverage.xml'